

variables:
  #git 邮箱
  GIT_USEREMAIL: 1442190496@qq.com
  #git 用户名
  GIT_USERNAME: zhanqinghui


# 定义 stages
stages:
  - build_imx6

#缓存路径
cache: 
  key: ${CI_BUILD_STAGE}
  paths:
    - build/
    - ebf_linux_kernel/
    - ebf_linux_uboot/
    - git/
    
# 定义 build_image  job
build_image:

  tags: 
    - ENABLE

  stage: build_imx6

  #指定分支更新进行编译
  only:
    - CI/CD_test

  before_script:
 
    - git config --global user.email "$GIT_USEREMAIL"
    - git config --global user.name "$GIT_USERNAME"

    - time=$(date +%Y-%m-%d)
    - image_dir="/mnt/share/$time"
    #- chmod +x ./env/ci_imx6.sh

  script:


    #- cd /opt/ebf-image-builder
    #- git pull
    #- chmod +x /opt/ebf-image-builder/env/ci_imx6.sh
    
    
    #编译镜像
    #- /opt/ebf-image-builder/env/ci_imx6.sh
    - ./env/ci_imx6.sh

    #拷贝到指定文件夹
    #- mkdir -p  "$image_dir"
    #- cp build/u-boot-*.imx  "$image_dir"
    #- cp build/debs/linux-image*.deb  "$image_dir"
    #- cp deploy/*/*.img  "$image_dir"

    #压缩img镜像为xz格式
    #- xz -z "$image_dir"/*.img


