
# 定义 stages
stages:
  - build_imx6
#  - build_output

# 定义 job
job1:

  tags: 
    - ENABLE
  stage: build_imx6

  script:
    - chmod +x ./env/ci_imx6.sh
    #- ./env/ci_imx6.sh
    - pwd
    - ls /mnt/
    - ls /mnt/share/

    #- cp  build/u-boot-*.imx  /mnt/share

