

variables:
  #git 邮箱
  GIT_USEREMAIL: 1442190496@qq.com
  #git 用户名
  GIT_USERNAME: zhanqinghui

  #image-builder的存放目录
  IMAGE_BUILDER_DIR: /opt/ebf-image-builder
 

# 定义 stages
stages:
  - build_image
  - build_output


# 定义 build_image  job
build_image_job:

  tags: 
    - ENABLE

  stage: build_image

  #指定分支更新进行编译
  only:
    - CI/CD_test
    #- master

  before_script:
 
    - git config --global user.email "$GIT_USEREMAIL"
    - git config --global user.name "$GIT_USERNAME"

  script:

    #
    - cd $IMAGE_BUILDER_DIR

    #test
    #拉取image-builder更新
    #- sleep 20     
    - git fetch --all
    - git reset --hard CI/CD_test
    - git pull
    - chmod +x  ./env/test.sh
    - ./env/test.sh $CI_COMMIT_BRANCH
    

    #编译镜像
    #- ./env/ci_builder.sh  imx6ull_pro_console_def.conf

build_output_job:

  tags: 
    - ENABLE

  stage: build_output

  #指定分支更新进行编译
  only:
    #- CI/CD_test
    - master

  before_script:
    - time=$(date +%Y-%m-%d)
    - image_dir="/mnt/share/$time"    

  script:
    #拷贝文件
    - mkdir -p  "$image_dir"
    - cp $IMAGE_BUILDER_DIR/build/u-boot-*.imx                       "$image_dir"     #uboot
    - cp $IMAGE_BUILDER_DIR/build/images/arch/arm/boot/zImage        "$image_dir"     #内核
    - cp $IMAGE_BUILDER_DIR/build/images/arch/arm/boot/dts/*npi.dtb  "$image_dir"     #设备树
    - cp $IMAGE_BUILDER_DIR/build/debs/linux-image*.deb              "$image_dir"     #内核deb包
    - cp $IMAGE_BUILDER_DIR/deploy/*$time*.tar                       "$image_dir"     #根文件系统
    - cp "$IMAGE_BUILDER_DIR"/deploy/*$time*/*.img  "$image_dir"                      #完整的img镜像

    #压缩img镜像为xz格式
    #- xz -z $image_dir/*.img

    #删除临时文件夹
    - rm -r $IMAGE_BUILDER_DIR/ignore
